# Setup
title:               litlinglab
tagline:             'a blog documenting ideas and research (drafts) in the fields of computational & digital humanities'
description:         #'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://aepfelchen.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
future: true
published: true

# About/contact
author:
  name:              Gwanghun Park
  url:               https://aepfelchen.github.io/about-us/
  email:             gwanghun.park.privat@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
